---
# tasks file for java8
- name: add java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Accept Java 8 Licence
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-8-licence-acceptance

# Common configurations to be run on all hosts
- name: Install default packages
  apt: pkg={{item}} state=latest cache_valid_time=3600
  with_items:
  - oracle-java8-installer
  - oracle-java8-set-default
    #- libt1-dev
  tags:
    - apt
