---
- name: Install git and maven
  apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - maven
    - unzip
  tags:
    - neo4j

- name: Clean neo4j
  file: path=/opt/exakat/neo4j state=absent

- name: update ulimit to 40000
  lineinfile: dest=/etc/security/limits.conf  line={{ item }}
  with_items:
    - "neo4j   soft    nofile  40000"
    - "neo4j   hard    nofile  40000"

- name: Downlad neo4j 2.3.7
  get_url: url=http://dist.neo4j.org/neo4j-community-2.3.7-unix.tar.gz dest=/opt/exakat/neo4j.tar.gz mode=0750
  tags:
    - neo4j

- name: Unzip neo4j
  unarchive: src=/opt/exakat/neo4j.tar.gz dest=/opt/exakat copy=no
  tags:
    - neo4j

- name: Rename neo4j distribution to neo4j
  shell: mv /opt/exakat/neo4j-community-2.3.7 /opt/exakat/neo4j
  tags:
    - neo4j

- name: Clean neo4j-gremlin-plugin
  file: path=/opt/exakat/neo4j-gremlin-plugin state=absent

- name: Clone gremlin neo4j
  git: repo=https://github.com/thinkaurelius/neo4j-gremlin-plugin.git dest=/opt/exakat/neo4j-gremlin-plugin
  tags:
    - neo4j

- name: Configure neo4j for gremlin 3.0
  lineinfile: dest=/opt/exakat/neo4j/conf/neo4j-server.properties regexp="^#org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.examples.server.unmanaged=/examples/unmanaged" insertafter="^#org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.examples.server.unmanaged=/examples/unmanaged" line="org.neo4j.server.thirdparty_jaxrs_classes=com.thinkaurelius.neo4j.plugins=/tp\n"
  tags:
    - neo4j

- name: Remove authentication for neo4j 2.3*
  lineinfile: dest=/opt/exakat/neo4j/conf/neo4j-server.properties regexp="dbms.security.auth_enabled=true" line="dbms.security.auth_enabled=false"
  tags:
    - neo4j

- name: Add sonatype repository to pom.xml
  lineinfile: dest=/opt/exakat/neo4j-gremlin-plugin/pom.xml regexp="    </contributors>" line="    </contributors>\n  \n  <repositories>\n   <repository>\n     <id>snapshots-repo</id>\n     <url>https://oss.sonatype.org/content/repositories/snapshots</url>\n     <releases><enabled>false</enabled></releases>\n     <snapshots><enabled>true</enabled></snapshots>\n   </repository>\n </repositories>\n"

- name: Adapt gremlin compilation
  lineinfile: dest={{ item.dest }} regexp={{ item.regexp }} line={{ item.line }}
  with_items:
    - {dest: "/opt/exakat/neo4j-gremlin-plugin/pom.xml", regexp: "<version>2.3.1</version>", line: "<version>2.3.5</version>"}
    - {dest: "/opt/exakat/neo4j-gremlin-plugin/tinkerpop2/pom.xml", regexp: "<version>2.3.1</version>", line: "<version>2.3.5</version>"}
    - {dest: "/opt/exakat/neo4j-gremlin-plugin/tinkerpop3/pom.xml", regexp: "<version>2.3.1</version>", line: "<version>2.3.5</version>"}
    - {dest: "/opt/exakat/neo4j-gremlin-plugin/tinkerpop3/pom.xml", regexp: "<tinkerpop-version>3.1.0-incubating</tinkerpop-version>", line: "<tinkerpop-version>3.2.0-incubating</tinkerpop-version>"}

- name: Build gremlin 3.0
  shell: cd /opt/exakat/neo4j-gremlin-plugin; mvn -T 2C clean package -Dtp.version=3
  tags:
    - neo4j

- name: Create gremlin directory
  file: path=/opt/exakat/neo4j/plugins/gremlin-plugin state=directory mode=0755

- name: Unzip gremlin to neo4j plugins
  unarchive: src=/opt/exakat/neo4j-gremlin-plugin/target/neo4j-gremlin-plugin-tp3-2.3.5-server-plugin.zip dest=/opt/exakat/neo4j/plugins/gremlin-plugin/ copy=no

- name: Clean neo4j-gremlin-plugin
  file: path=/opt/exakat/neo4j-gremlin-plugin state=absent
  tags:
    - neo4j

- name: Create scripts directory
  file: path=/opt/exakat/neo4j/scripts state=directory mode=0755
  tags:
    - neo4j
