---
- name: download latest exakat
  get_url: url=http://dist.exakat.io/versions/index.php?file=latest dest=/opt/exakat/exakat.phar
  tags:
    - exakat

- name: run doctor
  shell: cd /opt/exakat/; php exakat.phar doctor
  tags:
    - exakat
